# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cded8bf64701662a820952beca8129b8fcf0c7682b65be15b67bfbbcfe5534b6ba5a7bca2220deef65261eaa6c8ff3674a87daf935cf432255f5236ba7a53468

test:
  secret_key_base: 554db746758b7c6a57939929407500abe52016a2793a5dea2e532441850a2bbc8b962bc4bda6f64c43e9f7e309f8174249921455239568339e95892b12586201

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
